language: node_js
node_js:
  - stable

branches:
  only:
  - master
  - develop

install:
  - npm install
  - npm install -g ionic
  - npm install -g firebase-tools

script:
  - ionic build --prod

after_script:
  - firebase deploy --token $FIREBASE_TOKEN